### ISSUE TITLE
Composer out-of-date

### ISSUE THREAD

**Issue by DynamoGeek** [PokemonTCG/pokemon-tcg-sdk-php#2]
Hey, thanks for the wrapper!

I see that you've added imageUrlHiRes to the project here on GitHub, but it doesn't look like that change made it into composer.

**Comment by mmonkey** [comment]
Should be fixed, just had to create a new [release](/PokemonTCG/pokemon-tcg-sdk-php/releases/tag/1.1.0).

**Comment by DynamoGeek** [comment]
Confirmed.

EDIT: Quite the speedy response! Thanks for the assist.
