### ISSUE TITLE
Card not found with identifier: ex10-?

### ISSUE THREAD

**Issue by kylewhat** [PokemonTCG/pokemon-tcg-sdk-php#7]
this does not find this card

`$card = Pokemon::Card($options)->find('ex10-?'); `

below does find the card.  is the ex10-? incorrect for this?
`$card = Pokemon::Card($options)->where(['name' => 'Unown'])->where(['number' => '?'])->all();`

**Comment by mmonkey** [comment]
The `q` or query parameter will be supported in v2, which will support wildcard queries. See #9.
